require'nvim-treesitter.configs'.setup{
    ensure_installed = {
        "ada",
        "bash",
        "c",
        "c_sharp",
        "cmake",
        "cpp",
        "css",
        "csv",
        "d",
        "diff",
        "doxygen",
        "fortran",
        "fsharp",
        "gdscript",
        "go",
        "html",
        "javascript",
        "json",
        'markdown',
        "markdown_inline",
        "python",
        "rust",
        "regex",
        "xml",
        "yaml",
        "zig",
    },
    sync_install = false,
    auto_install = true,
    highlight = {
        enable = true,
    },
}
